export const EVENT_VENDOR_CATEGORIES = [
  { value: "venue", label: "Locații și săli de evenimente" },
  { value: "catering", label: "Catering și servicii culinare" },
  { value: "photography", label: "Fotografi și cameramani" },
  { value: "music", label: "Muzică și divertisment" },
  { value: "flowers", label: "Florărie și decorațiuni florale" },
  { value: "decoration", label: "Decorațiuni și design" },
  { value: "wedding-dress", label: "Rochii de mireasă și costume" },
  { value: "jewelry", label: "Bijuterii și accesorii" },
  { value: "beauty", label: "Servicii de frumusețe" },
  { value: "transportation", label: "Transport și limuzine" },
  { value: "cake", label: "Torturi și dulciuri" },
  { value: "invitations", label: "Invitații și papetărie" },
  { value: "gifts", label: "Marturii și cadouri" },
  { value: "planning", label: "Wedding planneri" },
  { value: "religious", label: "Servicii religioase" },
  { value: "other", label: "Alte servicii" },
];

export const ROMANIA_LOCATIONS = [
  { value: "bucharest", label: "București" },
  { value: "cluj-napoca", label: "Cluj-Napoca" },
  { value: "timisoara", label: "Timișoara" },
  { value: "iasi", label: "Iași" },
  { value: "constanta", label: "Constanța" },
  { value: "craiova", label: "Craiova" },
  { value: "brasov", label: "Brașov" },
  { value: "galati", label: "Galați" },
  { value: "ploiesti", label: "Ploiești" },
  { value: "oradea", label: "Oradea" },
  { value: "braila", label: "Brăila" },
  { value: "arad", label: "Arad" },
  { value: "pitesti", label: "Pitești" },
  { value: "sibiu", label: "Sibiu" },
  { value: "bacau", label: "Bacău" },
  { value: "targu-mures", label: "Târgu Mureș" },
  { value: "baia-mare", label: "Baia Mare" },
  { value: "buzau", label: "Buzău" },
  { value: "botosani", label: "Botoșani" },
  { value: "satu-mare", label: "Satu Mare" },
  { value: "ramnicu-valcea", label: "Râmnicu Vâlcea" },
  { value: "suceava", label: "Suceava" },
  { value: "piatra-neamt", label: "Piatra Neamț" },
  { value: "drobeta-turnu-severin", label: "Drobeta-Turnu Severin" },
  { value: "focsani", label: "Focșani" },
  { value: "tulcea", label: "Tulcea" },
  { value: "targoviste", label: "Târgoviște" },
  { value: "resita", label: "Reșița" },
  { value: "alba-iulia", label: "Alba Iulia" },
  { value: "bistrita", label: "Bistrița" },
  { value: "slatina", label: "Slatina" },
  { value: "calarasi", label: "Călărași" },
  { value: "deva", label: "Deva" },
  { value: "hunedoara", label: "Hunedoara" },
  { value: "miercurea-ciuc", label: "Miercurea Ciuc" },
  { value: "sfantu-gheorghe", label: "Sfântu Gheorghe" },
  { value: "alexandria", label: "Alexandria" },
  { value: "rosiorii-de-vede", label: "Roșiorii de Vede" },
  { value: "giurgiu", label: "Giurgiu" },
  { value: "slobozia", label: "Slobozia" },
  { value: "vaslui", label: "Vaslui" },
  { value: "zalau", label: "Zalău" },
];
